AllCops:
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.0.1
  Exclude:
    - 'db/schema.rb'
    - 'db_origami/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'spec/**/*'

Layout/SpaceInLambdaLiteral:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Naming/PredicateName:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
